import { Config, DatasetMeta, getDataset, mlpHiddenLayers, fmtLr, archSummary } from "./types";

/** Generates a complete, runnable single-file PyTorch training script. */
export function generateTrainPy(cfg: Config, meta: DatasetMeta): string {
  const L: string[] = [];
  const isReg = cfg.task === "tabular-reg";
  const isImage = cfg.task === "image-class";
  const isText = cfg.task === "text-class";
  const hidden = mlpHiddenLayers(cfg.mlpPreset).join(", ");
  const outDim = isReg ? 1 : meta.classes;
  const inC = cfg.datasetId === "cifar10" ? 3 : 1;

  L.push(`"""`);
  L.push(`${cfg.name || "torchforge-run"} — generated by TorchForge`);
  L.push(`task: ${cfg.task}   dataset: ${meta.label}   arch: ${cfg.arch}`);
  L.push(`Run:  pip install torch${isImage ? " torchvision" : ""}${isText ? " torchtext" : ""}${meta.source === "sklearn" || meta.source === "custom" ? " scikit-learn pandas" : ""}`);
  L.push(`      python train.py`);
  L.push(`"""`);
  L.push(`import json, math, random, time`);
  L.push(`import numpy as np`);
  L.push(`import torch`);
  L.push(`import torch.nn as nn`);
  L.push(`import torch.nn.functional as F`);
  L.push(`from torch.utils.data import DataLoader, TensorDataset, random_split`);
  if (isImage) {
    L.push(`from torchvision import datasets, transforms`);
  }
  if (isText) {
    L.push(`from torchtext.datasets import ${cfg.datasetId === "agnews" ? "AG_NEWS" : "IMDB"}`);
    L.push(`from torchtext.data.utils import get_tokenizer`);
    L.push(`from torchtext.vocab import build_vocab_from_iterator`);
    L.push(`from torch.nn.utils.rnn import pad_sequence`);
  }
  if (meta.source === "sklearn" || meta.source === "custom") {
    L.push(`from sklearn.model_selection import train_test_split`);
    L.push(`from sklearn.preprocessing import StandardScaler`);
  }
  if (meta.source === "custom") {
    L.push(`import pandas as pd`);
  }
  L.push(``);
  L.push(`CONFIG = {`);
  L.push(`    "task": "${cfg.task}",`);
  L.push(`    "dataset": "${cfg.datasetId}",`);
  L.push(`    "arch": "${cfg.arch}",`);
  L.push(`    "val_split": ${cfg.valSplit / 100},`);
  L.push(`    "test_split": ${cfg.testSplit / 100},`);
  L.push(`    "batch_size": ${cfg.batch},`);
  L.push(`    "epochs": ${cfg.epochs},`);
  L.push(`    "lr": ${cfg.lr},`);
  L.push(`    "weight_decay": ${cfg.weightDecay},`);
  L.push(`    "optimizer": "${cfg.optimizer}",`);
  L.push(`    "scheduler": "${cfg.scheduler}",`);
  L.push(`    "patience": ${cfg.patience},`);
  L.push(`    "dropout": ${cfg.dropout},`);
  L.push(`    "seed": ${cfg.seed},`);
  L.push(`    "device": "${cfg.device}",`);
  L.push(`}`);
  L.push(``);
  L.push(`def set_seed(seed: int):`);
  L.push(`    random.seed(seed); np.random.seed(seed); torch.manual_seed(seed)`);
  L.push(`    torch.cuda.manual_seed_all(seed)`);
  L.push(`    torch.backends.cudnn.deterministic = True`);
  L.push(``);

  /* ---------------- data ---------------- */
  L.push(`# ---------------- data ----------------`);
  if (isImage) {
    const dsCls = cfg.datasetId === "cifar10" ? "CIFAR10" : cfg.datasetId === "fashionmnist" ? "FashionMNIST" : "MNIST";
    const mean = cfg.datasetId === "cifar10" ? "(0.4914, 0.4822, 0.4465)" : "(0.5,)";
    const std = cfg.datasetId === "cifar10" ? "(0.2470, 0.2435, 0.2616)" : "(0.5,)";
    L.push(`def build_data():`);
    if (cfg.augment) {
      L.push(`    train_tf = transforms.Compose([`);
      if (cfg.datasetId === "cifar10") {
        L.push(`        transforms.RandomCrop(32, padding=4),`);
        L.push(`        transforms.RandomHorizontalFlip(),`);
      } else {
        L.push(`        transforms.RandomAffine(degrees=8, translate=(0.08, 0.08)),`);
      }
      L.push(`        transforms.ToTensor(),`);
      L.push(`        transforms.Normalize(${mean}, ${std}),`);
      L.push(`    ])`);
    } else {
      L.push(`    train_tf = transforms.Compose([transforms.ToTensor(), transforms.Normalize(${mean}, ${std})])`);
    }
    L.push(`    test_tf = transforms.Compose([transforms.ToTensor(), transforms.Normalize(${mean}, ${std})])`);
    L.push(`    full_train = datasets.${dsCls}("./data", train=True, download=True, transform=train_tf)`);
    L.push(`    test_ds = datasets.${dsCls}("./data", train=False, download=True, transform=test_tf)`);
    L.push(`    n_val = int(len(full_train) * CONFIG["val_split"])`);
    L.push(`    train_ds, val_ds = random_split(full_train, [len(full_train) - n_val, n_val],`);
    L.push(`                                    generator=torch.Generator().manual_seed(CONFIG["seed"]))`);
    L.push(`    return train_ds, val_ds, test_ds`);
  } else if (isText) {
    const dsName = cfg.datasetId === "agnews" ? "AG_NEWS" : "IMDB";
    L.push(`tokenizer = get_tokenizer("basic_english")`);
    L.push(``);
    L.push(`def build_data():`);
    L.push(`    def yield_tokens(data_iter):`);
    L.push(`        for _, text in data_iter:`);
    L.push(`            yield tokenizer(text)`);
    L.push(`    vocab = build_vocab_from_iterator(yield_tokens(${dsName}(split="train")),`);
    L.push(`                                      max_tokens=${cfg.vocabSize}, specials=["<unk>"])`);
    L.push(`    vocab.set_default_index(vocab["<unk>"])`);
    L.push(`    def to_idx(label, text):`);
    const labelFix = cfg.datasetId === "imdb" ? `int(label) - 1` : `int(label) - 1`;
    L.push(`        ids = vocab(tokenizer(text))[:${cfg.maxLen}]`);
    L.push(`        return ${labelFix}, torch.tensor(ids, dtype=torch.long)`);
    L.push(`    full = [to_idx(l, t) for l, t in ${dsName}(split="train")]`);
    L.push(`    test = [to_idx(l, t) for l, t in ${dsName}(split="test")]`);
    L.push(`    n_val = int(len(full) * CONFIG["val_split"])`);
    L.push(`    gen = torch.Generator().manual_seed(CONFIG["seed"])`);
    L.push(`    train, val = random_split(full, [len(full) - n_val, n_val], generator=gen)`);
    L.push(`    def collate(batch):`);
    L.push(`        labels, texts = zip(*batch)`);
    L.push(`        texts = pad_sequence(texts, batch_first=True, padding_value=vocab["<pad>"] if "<pad>" in vocab else 0)`);
    L.push(`        return texts, torch.tensor(labels, dtype=torch.long)`);
    L.push(`    return (train, val, test), collate`);
  } else {
    // tabular
    if (meta.source === "sklearn") {
      const loader =
        cfg.datasetId === "wine" ? "load_wine()" :
        cfg.datasetId === "breastcancer" ? "load_breast_cancer()" :
        cfg.datasetId === "housing" ? "fetch_california_housing()" : "load_diabetes()";
      L.push(`def build_data():`);
      L.push(`    from sklearn.datasets import ${loader.split("(")[0]}`);
      L.push(`    raw = ${loader}`);
      L.push(`    X, y = raw.data.astype("float32"), raw.target.astype("${isReg ? "float32" : "int64"}")`);
    } else {
      L.push(`def build_data():  # expects data.csv with feature columns + '${isReg ? "target" : "label"}'`);
      L.push(`    df = pd.read_csv("data.csv")`);
      if (isReg) {
        L.push(`    X = df.drop(columns=["target"]).values.astype("float32")`);
        L.push(`    y = df["target"].values.astype("float32")`);
      } else {
        L.push(`    X = df.drop(columns=["label"]).values.astype("float32")`);
        L.push(`    y = df["label"].astype("category").cat.codes.values.astype("int64")`);
      }
    }
    L.push(`    Xtr, Xtmp, ytr, ytmp = train_test_split(X, y, test_size=CONFIG["val_split"] + CONFIG["test_split"],`);
    L.push(`                                            random_state=CONFIG["seed"], ${isReg ? "" : "stratify=y"})`);
    L.push(`    frac = CONFIG["test_split"] / (CONFIG["val_split"] + CONFIG["test_split"])`);
    L.push(`    Xva, Xte, yva, yte = train_test_split(Xtmp, ytmp, test_size=frac, random_state=CONFIG["seed"]${isReg ? "" : ", stratify=ytmp"})`);
    L.push(`    scaler = StandardScaler().fit(Xtr)`);
    L.push(`    def ds(x, t): return TensorDataset(torch.tensor(scaler.transform(x), dtype=torch.float32), torch.tensor(t))`);
    L.push(`    return ds(Xtr, ytr), ds(Xva, yva), ds(Xte, yte)`);
  }
  L.push(``);

  /* ---------------- model ---------------- */
  L.push(`# ---------------- model ----------------`);
  if (cfg.arch === "mlp") {
    L.push(`class Model(nn.Module):`);
    L.push(`    def __init__(self):`);
    L.push(`        super().__init__()`);
    L.push(`        dims = [${meta.inDim}, ${hidden}, ${outDim}]`);
    L.push(`        blocks = []`);
    L.push(`        for i in range(len(dims) - 2):`);
    L.push(`            blocks.append(nn.Linear(dims[i], dims[i + 1]))`);
    if (cfg.batchNorm) L.push(`            blocks.append(nn.BatchNorm1d(dims[i + 1]))`);
    L.push(`            blocks.append(nn.ReLU())`);
    if (cfg.dropout > 0) L.push(`            blocks.append(nn.Dropout(${cfg.dropout}))`);
    L.push(`        blocks.append(nn.Linear(dims[-2], dims[-1]))`);
    L.push(`        self.net = nn.Sequential(*blocks)`);
    L.push(`    def forward(self, x):`);
    if (isImage) L.push(`        x = x.flatten(1)`);
    L.push(`        return self.net(x).squeeze(-1)`);
  } else if (cfg.arch === "cnn" || cfg.arch === "deeper-cnn") {
    const f = cfg.cnnFilters;
    L.push(`class Model(nn.Module):`);
    L.push(`    def __init__(self, num_classes=${outDim}):`);
    L.push(`        super().__init__()`);
    L.push(`        self.features = nn.Sequential(`);
    L.push(`            nn.Conv2d(${inC}, ${f}, 3, padding=1), nn.ReLU(),`);
    L.push(`            nn.MaxPool2d(2),`);
    L.push(`            nn.Conv2d(${f}, ${f * 2}, 3, padding=1), nn.ReLU(),`);
    L.push(`            nn.MaxPool2d(2),`);
    if (cfg.arch === "deeper-cnn") {
      L.push(`            nn.Conv2d(${f * 2}, ${f * 4}, 3, padding=1), nn.ReLU(),`);
      L.push(`            nn.MaxPool2d(2),`);
    }
    L.push(`        )`);
    if (cfg.dropout > 0) L.push(`        self.drop = nn.Dropout2d(${cfg.dropout})`);
    L.push(`        self.head = nn.Sequential(nn.LazyLinear(256), nn.ReLU(), nn.Linear(256, num_classes))`);
    L.push(`    def forward(self, x):`);
    L.push(`        x = self.features(x)`);
    if (cfg.dropout > 0) L.push(`        x = self.drop(x)`);
    L.push(`        return self.head(x.flatten(1))`);
  } else if (cfg.arch === "lstm") {
    L.push(`class Model(nn.Module):`);
    L.push(`    def __init__(self, vocab=${cfg.vocabSize}, num_classes=${outDim}):`);
    L.push(`        super().__init__()`);
    L.push(`        self.emb = nn.Embedding(vocab, 128, padding_idx=0)`);
    L.push(`        self.rnn = nn.LSTM(128, ${cfg.lstmHidden}, num_layers=${cfg.lstmLayers}, batch_first=True,`);
    L.push(`                           dropout=${cfg.lstmLayers > 1 ? cfg.dropout : 0}, bidirectional=${cfg.bidirectional ? "True" : "False"})`);
    if (cfg.dropout > 0) L.push(`        self.drop = nn.Dropout(${cfg.dropout})`);
    L.push(`        self.fc = nn.Linear(${cfg.bidirectional ? 2 * cfg.lstmHidden : cfg.lstmHidden}, num_classes)`);
    L.push(`    def forward(self, x):`);
    L.push(`        h, _ = self.rnn(self.emb(x))`);
    L.push(`        h = h[:, -1, :]`);
    if (cfg.dropout > 0) L.push(`        h = self.drop(h)`);
    L.push(`        return self.fc(h)`);
  } else {
    L.push(`class Model(nn.Module):`);
    L.push(`    def __init__(self, vocab=${cfg.vocabSize}, num_classes=${outDim}):`);
    L.push(`        super().__init__()`);
    L.push(`        self.emb = nn.Embedding(vocab, ${cfg.tfmDim}, padding_idx=0)`);
    L.push(`        self.pos = nn.Embedding(512, ${cfg.tfmDim})`);
    L.push(`        layer = nn.TransformerEncoderLayer(${cfg.tfmDim}, nhead=${Math.max(2, Math.round(cfg.tfmDim / 32))},`);
    L.push(`                                           dim_feedforward=${cfg.tfmDim * 4}, dropout=${cfg.dropout}, batch_first=True)`);
    L.push(`        self.enc = nn.TransformerEncoder(layer, num_layers=${cfg.tfmLayers})`);
    L.push(`        self.fc = nn.Linear(${cfg.tfmDim}, num_classes)`);
    L.push(`    def forward(self, x):`);
    L.push(`        idx = torch.arange(x.size(1), device=x.device)`);
    L.push(`        h = self.emb(x) + self.pos(idx)`);
    L.push(`        h = self.enc(h, src_key_padding_mask=(x == 0))`);
    L.push(`        mask = (x != 0).unsqueeze(-1).float()`);
    L.push(`        h = (h * mask).sum(1) / mask.sum(1).clamp(min=1)`);
    L.push(`        return self.fc(h)`);
  }
  L.push(``);

  /* ---------------- metrics ---------------- */
  L.push(`# ---------------- metrics ----------------`);
  if (!isReg) {
    L.push(`def confusion(preds, targets, k=${outDim}):`);
    L.push(`    return torch.bincount(targets * k + preds, minlength=k * k).view(k, k)`);
    L.push(``);
    L.push(`def classification_report(cm):`);
    L.push(`    cm = cm.float()`);
    L.push(`    tp = cm.diag(); fp = cm.sum(0) - tp; fn = cm.sum(1) - tp`);
    L.push(`    prec = tp / (tp + fp).clamp(min=1); rec = tp / (tp + fn).clamp(min=1)`);
    L.push(`    f1 = 2 * prec * rec / (prec + rec).clamp(min=1e-9)`);
    L.push(`    return {"accuracy": (tp.sum() / cm.sum()).item(),`);
    L.push(`            "precision_macro": prec.mean().item(),`);
    L.push(`            "recall_macro": rec.mean().item(),`);
    L.push(`            "f1_macro": f1.mean().item()}`);
  } else {
    L.push(`def regression_report(preds, targets):`);
    L.push(`    mae = (preds - targets).abs().mean()`);
    L.push(`    rmse = ((preds - targets) ** 2).mean().sqrt()`);
    L.push(`    r2 = 1 - ((targets - preds) ** 2).sum() / ((targets - targets.mean()) ** 2).sum().clamp(min=1e-9)`);
    L.push(`    return {"mae": mae.item(), "rmse": rmse.item(), "r2": r2.item()}`);
  }
  L.push(``);

  /* ---------------- loops ---------------- */
  L.push(`# ---------------- train / eval ----------------`);
  L.push(`def resolve_device(pref):`);
  L.push(`    if pref == "cpu": return torch.device("cpu")`);
  L.push(`    if pref == "cuda" or (pref == "auto" and torch.cuda.is_available()): return torch.device("cuda")`);
  L.push(`    if pref == "mps" or (pref == "auto" and torch.backends.mps.is_available()): return torch.device("mps")`);
  L.push(`    return torch.device("cpu")`);
  L.push(``);
  if (isText) {
    L.push(`@torch.no_grad()`);
    L.push(`def evaluate(model, loader, device, want_preds=False):`);
    L.push(`    model.eval(); preds, tgts = [], []`);
    L.push(`    for x, y in loader:`);
    L.push(`        x, y = x.to(device), y.to(device)`);
    L.push(`        logits = model(x)`);
    if (isReg) L.push(`        preds.append(logits); tgts.append(y)`);
    else L.push(`        preds.append(logits.argmax(-1)); tgts.append(y)`);
    L.push(`    preds, tgts = torch.cat(preds), torch.cat(tgts)`);
    if (isReg) L.push(`    return (preds, tgts) if want_preds else regression_report(preds, tgts)`);
    else L.push(`    return (preds, tgts) if want_preds else classification_report(confusion(preds, tgts))`);
  } else {
    L.push(`@torch.no_grad()`);
    L.push(`def evaluate(model, loader, device, want_preds=False):`);
    L.push(`    model.eval(); preds, tgts = [], []`);
    L.push(`    for x, y in loader:`);
    L.push(`        x, y = x.to(device), y.to(device)`);
    L.push(`        logits = model(x)`);
    if (isReg) L.push(`        preds.append(logits); tgts.append(y)`);
    else L.push(`        preds.append(logits.argmax(-1)); tgts.append(y)`);
    L.push(`    preds, tgts = torch.cat(preds), torch.cat(tgts)`);
    if (isReg) L.push(`    return (preds, tgts) if want_preds else regression_report(preds, tgts)`);
    else L.push(`    return (preds, tgts) if want_preds else classification_report(confusion(preds, tgts))`);
  }
  L.push(``);
  L.push(`def main():`);
  L.push(`    set_seed(CONFIG["seed"])`);
  L.push(`    device = resolve_device(CONFIG["device"])`);
  L.push(`    print(f"device: {device}")`);
  if (isText) {
    L.push(`    (train_ds, val_ds, test_ds), collate = build_data()`);
    L.push(`    kw = dict(batch_size=CONFIG["batch_size"], collate_fn=collate)`);
    L.push(`    train_dl = DataLoader(train_ds, shuffle=True, **kw)`);
    L.push(`    val_dl = DataLoader(val_ds, **kw); test_dl = DataLoader(test_ds, **kw)`);
  } else {
    L.push(`    train_ds, val_ds, test_ds = build_data()`);
    L.push(`    train_dl = DataLoader(train_ds, batch_size=CONFIG["batch_size"], shuffle=True)`);
    L.push(`    val_dl = DataLoader(val_ds, batch_size=CONFIG["batch_size"])`);
    L.push(`    test_dl = DataLoader(test_ds, batch_size=CONFIG["batch_size"])`);
  }
  L.push(`    model = Model().to(device)`);
  L.push(`    n_params = sum(p.numel() for p in model.parameters())`);
  L.push(`    print(f"params: {n_params:,}")`);
  if (isReg) L.push(`    loss_fn = nn.MSELoss()`);
  else L.push(`    loss_fn = nn.CrossEntropyLoss()`);
  L.push(`    wd = CONFIG["weight_decay"]`);
  L.push(`    if CONFIG["optimizer"] == "adam":  opt = torch.optim.Adam(model.parameters(), lr=CONFIG["lr"], weight_decay=wd)`);
  L.push(`    elif CONFIG["optimizer"] == "adamw": opt = torch.optim.AdamW(model.parameters(), lr=CONFIG["lr"], weight_decay=wd)`);
  L.push(`    else: opt = torch.optim.SGD(model.parameters(), lr=CONFIG["lr"], momentum=0.9, weight_decay=wd)`);
  L.push(`    if CONFIG["scheduler"] == "step":`);
  L.push(`        sched = torch.optim.lr_scheduler.StepLR(opt, step_size=max(1, CONFIG["epochs"] // 3), gamma=0.5)`);
  L.push(`    elif CONFIG["scheduler"] == "cosine":`);
  L.push(`        sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=CONFIG["epochs"])`);
  L.push(`    else:`);
  L.push(`        sched = None`);
  L.push(`    best, bad_epochs = math.inf, 0`);
  L.push(`    for epoch in range(1, CONFIG["epochs"] + 1):`);
  L.push(`        model.train(); run_loss, t0 = 0.0, time.time()`);
  L.push(`        for x, y in train_dl:`);
  L.push(`            x, y = x.to(device), y.to(device)`);
  L.push(`            opt.zero_grad()`);
  L.push(`            loss = loss_fn(model(x), y)`);
  L.push(`            loss.backward(); opt.step()`);
  L.push(`            run_loss += loss.item() * x.size(0)`);
  L.push(`        if sched is not None: sched.step()`);
  L.push(`        train_loss = run_loss / len(train_dl.dataset)`);
  L.push(`        val_rep = evaluate(model, val_dl, device)`);
  if (isReg) L.push(`        val_loss, val_key = val_rep["rmse"], "rmse"`);
  else L.push(`        val_loss, val_key = 1 - val_rep["accuracy"], "accuracy"`);
  L.push(`        lr = opt.param_groups[0]["lr"]`);
  L.push(`        print(f"epoch {epoch:02d}/{CONFIG['epochs']}  train_loss {train_loss:.4f}  val_{val_key} {val_rep[val_key]:.4f}  lr {lr:.2e}  ({time.time()-t0:.1f}s)")`);
  L.push(`        if val_loss < best:`);
  L.push(`            best, bad_epochs = val_loss, 0`);
  L.push(`            torch.save(model.state_dict(), "best.pt")`);
  L.push(`        elif CONFIG["patience"] > 0:`);
  L.push(`            bad_epochs += 1`);
  L.push(`            if bad_epochs >= CONFIG["patience"]:`);
  L.push(`                print("early stopping"); break`);
  L.push(`    model.load_state_dict(torch.load("best.pt", weights_only=True))`);
  L.push(`    report = evaluate(model, test_dl, device)`);
  L.push(`    print("test:", json.dumps(report, indent=2))`);
  L.push(`    json.dump({"config": CONFIG, "test": report}, open("metrics.json", "w"), indent=2)`);
  L.push(``);
  L.push(`if __name__ == "__main__":`);
  L.push(`    main()`);

  return L.join("\n");
}

export function generateConfigJson(cfg: Config, meta: DatasetMeta): string {
  const s = archSummary(cfg, meta);
  const obj = {
    experiment: cfg.name || `${meta.id}-${cfg.arch}`,
    task: cfg.task,
    dataset: { id: meta.id, label: meta.label, source: meta.source, samples: meta.samples, classes: meta.classes },
    splits: { val_pct: cfg.valSplit, test_pct: cfg.testSplit, augment: cfg.augment, text_max_len: cfg.maxLen },
    model: { arch: cfg.arch, parameters: s.total, dropout: cfg.dropout, batch_norm: cfg.batchNorm },
    training: { optimizer: cfg.optimizer, lr: cfg.lr, weight_decay: cfg.weightDecay, epochs: cfg.epochs, batch_size: cfg.batch, scheduler: cfg.scheduler, early_stopping_patience: cfg.patience, seed: cfg.seed, device: cfg.device },
    evaluation: { metrics: cfg.metrics, confusion_matrix: cfg.confusion },
  };
  return JSON.stringify(obj, null, 2);
}

export function pipCommand(cfg: Config, meta: DatasetMeta): string {
  const pkgs = ["torch"];
  if (cfg.task === "image-class") pkgs.push("torchvision");
  if (cfg.task === "text-class") pkgs.push("torchtext");
  if (meta.source === "sklearn" || meta.source === "custom") pkgs.push("scikit-learn", "pandas");
  return `pip install ${pkgs.join(" ")}`;
}

export { fmtLr };
